// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkdmkbqtvxqkkpafovlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrZG1rYnF0dnhxa2twYWZvdmx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjE5MjcsImV4cCI6MjA2NzAzNzkyN30.UC76d_HEx2LlNqJwBBoagTnI4yvc5MuJ0AtPJli2j0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});